[MODEL_INFO]
OPENAI_API_KEY = "" # Needed only for openAI models
MODEL_NAME = "h2ogpt-sql-sqlcoder-34b-alpha" # Others: e.g. gpt-4, gpt-4-32k, text-davinci-003
QUANT_TYPE = '4bit'

H2OGPT_URL = 'http://38.128.233.247'
H2OGPT_API_TOKEN = ""
H2OGPTE_URL = ""
H2OGPTE_API_TOKEN = ""
H2OGPT_BASE_URL = "https://api.gpt.h2o.ai/v1"
H2OGPT_BASE_API_TOKEN = ""


RECOMMENDATION_MODEL = "h2oai/h2ogpt-4096-llama2-70b-chat"
VULNERABILITY_SCANNER = "h2oai/h2ogpt-4096-llama2-70b-chat" # other options openai models depending on availability (e.g. 'gpt-3.5-turbo')
SELF_CORRECTION_MODEL = "h2oai/h2ogpt-4096-llama2-70b-chat" # other options openai models depending on availability (e.g. 'gpt-3.5-turbo')

[LOCAL_DB_CONFIG]
HOST_NAME = "localhost"
USER_NAME = "sqlite"
PASSWORD = "abc"
DB_NAME = "querydb"
PORT = "5432"

[LOGGING]
LOG-LEVEL = "DEBUG"

[DB-DIALECT]
DB_TYPE = "sqlite"

[TABLE_INFO]
TABLE_INFO_PATH = "examples/demo/table_info.jsonl"
SAMPLE_QNA_PATH = "examples/demo/demo_qa.csv"
TABLE_SAMPLES_PATH = "examples/demo/demo_data.csv"
TABLE_NAME = "demo"
